In [14]:
import pandas as pd
import numpy as np

In [15]:
df=pd.read_csv('Absenteeism.csv')
df.head()

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0  11                  26                 7                3        1   
1  36                   0                 7                3        1   
2   3                  23                 7                4        1   
3   7                   7                 7                5        1   
4  11                  23                 7                5        1   

   Transportation expense  Distance from Residence to Work  Service time  Age  \
0                     289                               36            13   33   
1                     118                               13            18   50   
2                     179                               51            18   38   
3                     279                                5            14   39   
4                     289                               36            13   33   

   Work load Average/day   ...  Disciplinary failure  Education  Son  \
0                  239554  ...                     0          1    2   
1                  239554  ...                     1          1    1   
2                  239554  ...                     0          1    0   
3                  239554  ...                     0          1    2   
4                  239554  ...                     0          1    2   

   Social drinker  Social smoker  Pet  Weight  Height  Body mass index  \
0               1              0    1      90     172               30   
1               1              0    0      98     178               31   
2               1              0    0      89     170               31   
3               1              1    0      68     168               24   
4               1              0    1      90     172               30   

   Absenteeism time in hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2  

[5 rows x 21 columns]

# Create the targets

In [16]:
df['Absenteeism time in hours'].median()

3.0

In [17]:
Data=pd.DataFrame(df)


In [18]:
Data

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0    11                  26                 7                3        1   
1    36                   0                 7                3        1   
2     3                  23                 7                4        1   
3     7                   7                 7                5        1   
4    11                  23                 7                5        1   
..   ..                 ...               ...              ...      ...   
735  11                  14                 7                3        1   
736   1                  11                 7                3        1   
737   4                   0                 0                3        1   
738   8                   0                 0                4        2   
739  35                   0                 0                6        3   

     Transportation expense  Distance from Residence to Work  Service time  \
0                       289                               36            13   
1                       118                               13            18   
2                       179                               51            18   
3                       279                                5            14   
4                       289                               36            13   
..                      ...                              ...           ...   
735                     289                               36            13   
736                     235                               11            14   
737                     118                               14            13   
738                     231                               35            14   
739                     179                               45            14   

     Age  Work load Average/day   ...  Disciplinary failure  Education  Son  \
0     33                  239554  ...                     0          1    2   
1     50                  239554  ...                     1          1    1   
2     38                  239554  ...                     0          1    0   
3     39                  239554  ...                     0          1    2   
4     33                  239554  ...                     0          1    2   
..   ...                     ...  ...                   ...        ...  ...   
735   33                  264604  ...                     0          1    2   
736   37                  264604  ...                     0          3    1   
737   40                  271219  ...                     0          1    1   
738   39                  271219  ...                     0          1    2   
739   53                  271219  ...                     0          1    1   

     Social drinker  Social smoker  Pet  Weight  Height  Body mass index  \
0                 1              0    1      90     172               30   
1                 1              0    0      98     178               31   
2                 1              0    0      89     170               31   
3                 1              1    0      68     168               24   
4                 1              0    1      90     172               30   
..              ...            ...  ...     ...     ...              ...   
735               1              0    1      90     172               30   
736               0              0    1      88     172               29   
737               1              0    8      98     170               34   
738               1              0    2     100     170               35   
739               0              0    1      77     175               25   

     Absenteeism time in hours  
0                            4  
1                            0  
2                            2  
3                            4  
4                            2  
..                         ...  
735                          8  
736                          4  
737     

In [19]:
targets=np.where(df['Absenteeism time in hours']>3,1,0)

In [20]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [21]:
df['Excessive absenteeism']=targets


In [22]:
df.head()

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0  11                  26                 7                3        1   
1  36                   0                 7                3        1   
2   3                  23                 7                4        1   
3   7                   7                 7                5        1   
4  11                  23                 7                5        1   

   Transportation expense  Distance from Residence to Work  Service time  Age  \
0                     289                               36            13   33   
1                     118                               13            18   50   
2                     179                               51            18   38   
3                     279                                5            14   39   
4                     289                               36            13   33   

   Work load Average/day   ...  Education  Son  Social drinker  Social smoker  \
0                  239554  ...          1    2               1              0   
1                  239554  ...          1    1               1              0   
2                  239554  ...          1    0               1              0   
3                  239554  ...          1    2               1              1   
4                  239554  ...          1    2               1              0   

   Pet  Weight  Height  Body mass index  Absenteeism time in hours  \
0    1      90     172               30                          4   
1    0      98     178               31                          0   
2    0      89     170               31                          2   
3    0      68     168               24                          4   
4    1      90     172               30                          2   

   Excessive absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0  

[5 rows x 22 columns]

In [23]:
df.dtypes

ID                                 int64
Reason for absence                 int64
Month of absence                   int64
Day of the week                    int64
Seasons                            int64
Transportation expense             int64
Distance from Residence to Work    int64
Service time                       int64
Age                                int64
Work load Average/day              int64
Hit target                         int64
Disciplinary failure               int64
Education                          int64
Son                                int64
Social drinker                     int64
Social smoker                      int64
Pet                                int64
Weight                             int64
Height                             int64
Body mass index                    int64
Absenteeism time in hours          int64
Excessive absenteeism              int32
dtype: object

# A comment on the targets

In [24]:
targets.sum() / targets.shape[0]

0.4581081081081081

Note:46% of tagets are one's and 54 are zero's

In [26]:
data_with_targets is df

False

In [27]:
data_with_targets.head()

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0  11                  26                 7                3        1   
1  36                   0                 7                3        1   
2   3                  23                 7                4        1   
3   7                   7                 7                5        1   
4  11                  23                 7                5        1   

   Transportation expense  Distance from Residence to Work  Service time  Age  \
0                     289                               36            13   33   
1                     118                               13            18   50   
2                     179                               51            18   38   
3                     279                                5            14   39   
4                     289                               36            13   33   

   Work load Average/day   ...  Disciplinary failure  Education  Son  \
0                  239554  ...                     0          1    2   
1                  239554  ...                     1          1    1   
2                  239554  ...                     0          1    0   
3                  239554  ...                     0          1    2   
4                  239554  ...                     0          1    2   

   Social drinker  Social smoker  Pet  Weight  Height  Body mass index  \
0               1              0    1      90     172               30   
1               1              0    0      98     178               31   
2               1              0    0      89     170               31   
3               1              1    0      68     168               24   
4               1              0    1      90     172               30   

   Excessive absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0  

[5 rows x 21 columns]

# Select the inputs for the regression

In [28]:
data_with_targets.shape

(740, 21)

In [29]:
data_with_targets.iloc[:,0:20]

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0    11                  26                 7                3        1   
1    36                   0                 7                3        1   
2     3                  23                 7                4        1   
3     7                   7                 7                5        1   
4    11                  23                 7                5        1   
..   ..                 ...               ...              ...      ...   
735  11                  14                 7                3        1   
736   1                  11                 7                3        1   
737   4                   0                 0                3        1   
738   8                   0                 0                4        2   
739  35                   0                 0                6        3   

     Transportation expense  Distance from Residence to Work  Service time  \
0                       289                               36            13   
1                       118                               13            18   
2                       179                               51            18   
3                       279                                5            14   
4                       289                               36            13   
..                      ...                              ...           ...   
735                     289                               36            13   
736                     235                               11            14   
737                     118                               14            13   
738                     231                               35            14   
739                     179                               45            14   

     Age  Work load Average/day   Hit target  Disciplinary failure  Education  \
0     33                  239554          97                     0          1   
1     50                  239554          97                     1          1   
2     38                  239554          97                     0          1   
3     39                  239554          97                     0          1   
4     33                  239554          97                     0          1   
..   ...                     ...         ...                   ...        ...   
735   33                  264604          93                     0          1   
736   37                  264604          93                     0          3   
737   40                  271219          95                     0          1   
738   39                  271219          95                     0          1   
739   53                  271219          95                     0          1   

     Son  Social drinker  Social smoker  Pet  Weight  Height  Body mass index  
0      2               1              0    1      90     172               30  
1      1               1              0    0      98     178               31  
2      0               1              0    0      89     170               31  
3      2               1              1    0      68     168               24  
4      2               1              0    1      90     172               30  
..   ...             ...            ...  ...     ...     ...              ...  
735    2               1              0    1      90     172               30  
736    1               0              0    1      88     172               29  
737    1               1              0    8      98     170               34  
738    2               1              0    2     100     170               35  
739    1               0              0    1      77     175               25  

[740 rows x 20 columns]

In [30]:
data_with_targets.iloc[:,:-1]

ID  Reason for absence  Month of absence  Day of the week  Seasons  \
0    11                  26                 7                3        1   
1    36                   0                 7                3        1   
2     3                  23                 7                4        1   
3     7                   7                 7                5        1   
4    11                  23                 7                5        1   
..   ..                 ...               ...              ...      ...   
735  11                  14                 7                3        1   
736   1                  11                 7                3        1   
737   4                   0                 0                3        1   
738   8                   0                 0                4        2   
739  35                   0                 0                6        3   

     Transportation expense  Distance from Residence to Work  Service time  \
0                       289                               36            13   
1                       118                               13            18   
2                       179                               51            18   
3                       279                                5            14   
4                       289                               36            13   
..                      ...                              ...           ...   
735                     289                               36            13   
736                     235                               11            14   
737                     118                               14            13   
738                     231                               35            14   
739                     179                               45            14   

     Age  Work load Average/day   Hit target  Disciplinary failure  Education  \
0     33                  239554          97                     0          1   
1     50                  239554          97                     1          1   
2     38                  239554          97                     0          1   
3     39                  239554          97                     0          1   
4     33                  239554          97                     0          1   
..   ...                     ...         ...                   ...        ...   
735   33                  264604          93                     0          1   
736   37                  264604          93                     0          3   
737   40                  271219          95                     0          1   
738   39                  271219          95                     0          1   
739   53                  271219          95                     0          1   

     Son  Social drinker  Social smoker  Pet  Weight  Height  Body mass index  
0      2               1              0    1      90     172               30  
1      1               1              0    0      98     178               31  
2      0               1              0    0      89     170               31  
3      2               1              1    0      68     168               24  
4      2               1              0    1      90     172               30  
..   ...             ...            ...  ...     ...     ...              ...  
735    2               1              0    1      90     172               30  
736    1               0              0    1      88     172               29  
737    1               1              0    8      98     170               34  
738    2               1              0    2     100     170               35  
739    1               0              0    1      77     175               25  

[740 rows x 20 columns]

In [31]:
unscaled_inputs=data_with_targets.iloc[:,:-1]

In [40]:
unscaled_inputs.columns.values

array(['ID', 'Reason for absence', 'Month of absence', 'Day of the week',
       'Seasons', 'Transportation expense',
       'Distance from Residence to Work', 'Service time', 'Age',
       'Work load Average/day ', 'Hit target', 'Disciplinary failure',
       'Education', 'Son', 'Social drinker', 'Social smoker', 'Pet',
       'Weight', 'Height', 'Body mass index'], dtype=object)

In [33]:
columns_to_omit=['Absenteeism time in hours','Work load Average/day','Distance from Residence to work','Day of the week']

In [35]:
columns_to_scale=[x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

# standardize the data

In [38]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler=StandardScaler()

In [42]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [43]:
scaled_inputs=absenteeism_scaler.transform(unscaled_inputs)

In [44]:
scaled_inputs

array([[-0.63716146,  0.80493838,  0.19676258, ...,  0.85167289,
        -0.01904601,  0.77593223],
       [ 1.63271857, -2.28012426,  0.19676258, ...,  1.47305611,
         0.97582783,  1.00943766],
       [-1.36352307,  0.44896961,  0.19676258, ...,  0.77399998,
        -0.35067062,  1.00943766],
       ...,
       [-1.27272787, -2.28012426, -1.84169773, ...,  1.47305611,
        -0.35067062,  1.70995395],
       [-0.90954706, -2.28012426, -1.84169773, ...,  1.62840192,
        -0.35067062,  1.94345938],
       [ 1.54192337, -2.28012426, -1.84169773, ..., -0.15807485,
         0.47839091, -0.39159492]])

In [45]:
scaled_inputs.shape

(740, 20)

# Split the data into train and test

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
train_test_split(scaled_inputs,targets)

[array([[-0.45557106, -1.44953047, -0.67686327, ..., -0.70178518,
         -0.51648293, -0.39159492],
        [-0.54636626, -0.02565541, -1.2592805 , ..., -0.85713098,
          0.97582783, -1.32561663],
        [-1.00034226,  0.44896961,  0.19676258, ..., -0.85713098,
         -0.68229523, -0.62510035],
        ...,
        [-0.36477586,  1.04225089, -0.67686327, ...,  1.2400374 ,
          3.96044934, -0.39159492],
        [ 1.63271857, -0.73759294, -0.09444604, ...,  1.47305611,
          0.97582783,  1.00943766],
        [-1.45431827, -0.14431166,  0.48797119, ...,  0.69632708,
         -1.51135676,  1.47644852]]),
 array([[ 0.54317616, -0.73759294,  1.36159704, ..., -0.93480389,
         -0.35067062, -0.85860577],
        [ 0.90635696, -0.85624919,  1.65280566, ..., -0.77945808,
         -0.51648293, -0.62510035],
        [-1.36352307, -0.73759294,  0.77917981, ...,  0.77399998,
         -0.35067062,  1.00943766],
        ...,
        [ 0.90635696,  0.44896961, -1.2592805 , ..., -

In [48]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

In [49]:
print(x_train.shape,y_train.shape)

(592, 20) (592,)


In [50]:
print(x_test.shape,y_test.shape)

(148, 20) (148,)


# Logistic regression with sklearn

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

# Training the model

In [52]:
reg=LogisticRegression()

In [53]:
reg.fit(x_train,y_train)

LogisticRegression()

In [54]:
reg.score(x_train,y_train)

0.7516891891891891

# Manually check Accuracy

In [55]:
model_outputs=reg.predict(x_train)
model_outputs

array([1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,

In [56]:
y_train

array([1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,

In [57]:
model_outputs==y_train

array([ True,  True, False,  True, False,  True,  True,  True, False,
       False, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False,  True, False,  True, False, False,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True, False,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False,  True,

In [58]:
#total no of true entries
np.sum(model_outputs==y_train)

445

In [59]:
model_outputs.shape[0]

592

In [60]:
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.7516891891891891

# Finding the intercepts and coefficients

In [61]:
reg.intercept_

array([-0.24871861])

In [62]:
reg.coef_

array([[-0.40652762, -1.02570584,  0.28993083, -0.15682509, -0.30243708,
         0.39379832, -0.16474896, -0.51026731,  0.18641812,  0.13013898,
         0.06552447, -1.77236875, -0.1415844 ,  0.41850347,  0.29546466,
         0.15187649, -0.41264779,  0.66941113, -0.24619007, -0.5297908 ]])

In [63]:
unscaled_inputs.columns.values

array(['ID', 'Reason for absence', 'Month of absence', 'Day of the week',
       'Seasons', 'Transportation expense',
       'Distance from Residence to Work', 'Service time', 'Age',
       'Work load Average/day ', 'Hit target', 'Disciplinary failure',
       'Education', 'Son', 'Social drinker', 'Social smoker', 'Pet',
       'Weight', 'Height', 'Body mass index'], dtype=object)

In [64]:
feature_name=unscaled_inputs.columns.values

In [65]:
summary_table=pd.DataFrame(columns=['Feature_name'],data=feature_name)
summary_table['Coefficient']=np.transpose(reg.coef_)
summary_table

Feature_name  Coefficient
0                                ID    -0.406528
1                Reason for absence    -1.025706
2                  Month of absence     0.289931
3                   Day of the week    -0.156825
4                           Seasons    -0.302437
5            Transportation expense     0.393798
6   Distance from Residence to Work    -0.164749
7                      Service time    -0.510267
8                               Age     0.186418
9            Work load Average/day      0.130139
10                       Hit target     0.065524
11             Disciplinary failure    -1.772369
12                        Education    -0.141584
13                              Son     0.418503
14                   Social drinker     0.295465
15                    Social smoker     0.151876
16                              Pet    -0.412648
17                           Weight     0.669411
18                           Height    -0.246190
19                  Body mass index    -0.529791

In [66]:

summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Feature_name  Coefficient
0                         Intercept    -0.248719
1                                ID    -0.406528
2                Reason for absence    -1.025706
3                  Month of absence     0.289931
4                   Day of the week    -0.156825
5                           Seasons    -0.302437
6            Transportation expense     0.393798
7   Distance from Residence to Work    -0.164749
8                      Service time    -0.510267
9                               Age     0.186418
10           Work load Average/day      0.130139
11                       Hit target     0.065524
12             Disciplinary failure    -1.772369
13                        Education    -0.141584
14                              Son     0.418503
15                   Social drinker     0.295465
16                    Social smoker     0.151876
17                              Pet    -0.412648
18                           Weight     0.669411
19                           Height    -0.246190
20                  Body mass index    -0.529791

# Interpreting the coefficients

log(odds)=intercept+b1x+b2x+....

In [67]:
summary_table['Odds_ratio']=np.exp(summary_table.Coefficient)
summary_table

Feature_name  Coefficient  Odds_ratio
0                         Intercept    -0.248719    0.779799
1                                ID    -0.406528    0.665959
2                Reason for absence    -1.025706    0.358543
3                  Month of absence     0.289931    1.336335
4                   Day of the week    -0.156825    0.854854
5                           Seasons    -0.302437    0.739015
6            Transportation expense     0.393798    1.482602
7   Distance from Residence to Work    -0.164749    0.848107
8                      Service time    -0.510267    0.600335
9                               Age     0.186418    1.204926
10           Work load Average/day      0.130139    1.138987
11                       Hit target     0.065524    1.067719
12             Disciplinary failure    -1.772369    0.169930
13                        Education    -0.141584    0.867982
14                              Son     0.418503    1.519686
15                   Social drinker     0.295465    1.343751
16                    Social smoker     0.151876    1.164016
17                              Pet    -0.412648    0.661895
18                           Weight     0.669411    1.953087
19                           Height    -0.246190    0.781774
20                  Body mass index    -0.529791    0.588728

In [68]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature_name  Coefficient  Odds_ratio
18                           Weight     0.669411    1.953087
14                              Son     0.418503    1.519686
6            Transportation expense     0.393798    1.482602
15                   Social drinker     0.295465    1.343751
3                  Month of absence     0.289931    1.336335
9                               Age     0.186418    1.204926
16                    Social smoker     0.151876    1.164016
10           Work load Average/day      0.130139    1.138987
11                       Hit target     0.065524    1.067719
13                        Education    -0.141584    0.867982
4                   Day of the week    -0.156825    0.854854
7   Distance from Residence to Work    -0.164749    0.848107
19                           Height    -0.246190    0.781774
0                         Intercept    -0.248719    0.779799
5                           Seasons    -0.302437    0.739015
1                                ID    -0.406528    0.665959
17                              Pet    -0.412648    0.661895
8                      Service time    -0.510267    0.600335
20                  Body mass index    -0.529791    0.588728
2                Reason for absence    -1.025706    0.358543
12             Disciplinary failure    -1.772369    0.169930

A feature is not particularly important
--if its coefficient is around 0
--if its odds ratio is around 1

Backward elimination: the idea is that we can simplify our model by removing all features whch have close to no contribution to the model.